name: Mathcraft
main: io.github.pybsh.mathcraft.MathcraftPlugin
version: $version
api-version: '1.19'

author: pybsh

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20
  - io.github.monun:kommand-core:2.14.0
